### ISSUE TITLE
Error: Api contains errors

### ISSUE THREAD

**Issue by PatchRanger** [jayS-de/raml-php-generator#8]
During parsing the attached RAML-file, I've encountered the following errrors. Are they caused by incorrect syntax of the file - or by the reason of bugs in `raml-php-generator`? Please review.
Could we enhance the `raml-php-generator` in order to get this file parsed successfully?

[v1.raml.txt](https://github.com/jenschude/raml-php-generator/files/1870140/v1.raml.txt)

```
v1.raml (375, 9): Unknown node: value
v1.raml (373, 7): Missing required property content
v1.raml (378, 9): Unknown node: value
v1.raml (376, 7): Missing required property content
v1.raml (398, 9): Unknown node: value
v1.raml (396, 7): Missing required property content
v1.raml (401, 9): Unknown node: value
v1.raml (399, 7): Missing required property content
v1.raml (404, 9): Unknown node: value
v1.raml (402, 7): Missing required property content
v1.raml (407, 9): Unknown node: value
v1.raml (405, 7): Missing required property content
v1.raml (419, 7): Illegal override of property title inherited from DictionaryItem, required property can not be made optional 
v1.raml (609, 9): Unrecognized type 'datetime'.
v1.raml (612, 9): Unrecognized type 'datetime'.
v1.raml (758, 9): Unrecognized type 'datetime'.
v1.raml (928, 9): Unknown node: value
v1.raml (926, 7): Missing required property content
v1.raml (931, 9): Unknown node: value
v1.raml (929, 7): Missing required property content
v1.raml (934, 9): Unknown node: value
v1.raml (932, 7): Missing required property content
v1.raml (937, 9): Unknown node: value
v1.raml (935, 7): Missing required property content
v1.raml (940, 9): Unknown node: value
v1.raml (938, 7): Missing required property content
v1.raml (961, 9): Unknown node: value
v1.raml (959, 7): Missing required property content
v1.raml (964, 9): Unknown node: value
v1.raml (962, 7): Missing required property content
v1.raml (991, 9): Unknown node: value
v1.raml (989, 7): Missing required property content
v1.raml (994, 9): Unknown node: value
v1.raml (992, 7): Missing required property content
v1.raml (997, 9): Unknown node: value
v1.raml (995, 7): Missing required property content
v1.raml (1000, 9): Unknown node: value
v1.raml (998, 7): Missing required property content
v1.raml (1067, 9): Unknown node: value
v1.raml (1065, 7): Missing required property content
v1.raml (1070, 9): Unknown node: value
v1.raml (1068, 7): Missing required property content
v1.raml (1073, 9): Unknown node: value
v1.raml (1071, 7): Missing required property content
v1.raml (1082, 9): Unknown node: value
v1.raml (1080, 7): Missing required property content
v1.raml (1085, 9): Unknown node: value
v1.raml (1083, 7): Missing required property content
v1.raml (1088, 9): Unknown node: value
v1.raml (1086, 7): Missing required property content
v1.raml (1091, 9): Unknown node: value
v1.raml (1089, 7): Missing required property content
v1.raml (1100, 9): Unknown node: value
v1.raml (1098, 7): Missing required property content
v1.raml (1103, 9): Unknown node: value
v1.raml (1101, 7): Missing required property content
v1.raml (1106, 9): Unknown node: value
v1.raml (1104, 7): Missing required property content
v1.raml (1109, 9): Unknown node: value
v1.raml (1107, 7): Missing required property content
v1.raml (1112, 9): Unknown node: value
v1.raml (1110, 7): Missing required property content
v1.raml (1115, 9): Unknown node: value
v1.raml (1113, 7): Missing required property content
v1.raml (1118, 9): Unknown node: value
v1.raml (1116, 7): Missing required property content
v1.raml (1121, 9): Unknown node: value
v1.raml (1119, 7): Missing required property content
v1.raml (1136, 9): Unknown node: value
v1.raml (1134, 7): Missing required property content
v1.raml (1139, 9): Unknown node: value
v1.raml (1137, 7): Missing required property content
v1.raml (1142, 9): Unknown node: value
v1.raml (1140, 7): Missing required property content
v1.raml (1145, 9): Unknown node: value
v1.raml (1143, 7): Missing required property content
v1.raml (1148, 9): Unknown node: value
v1.raml (1146, 7): Missing required property content
v1.raml (1151, 9): Unknown node: value
v1.raml (1149, 7): Missing required property content
v1.raml (1154, 9): Unknown node: value
v1.raml (1152, 7): Missing required property content
v1.raml (1169, 9): Unknown node: value
v1.raml (1167, 7): Missing required property content
v1.raml (1172, 9): Unknown node: value
v1.raml (1170, 7): Missing required property content
v1.raml (1175, 9): Unknown node: value
v1.raml (1173, 7): Missing required property content
v1.raml (1178, 9): Unknown node: value
v1.raml (1176, 7): Missing required property content
v1.raml (1181, 9): Unknown node: value
v1.raml (1179, 7): Missing required property content
v1.raml (1184, 9): Unknown node: value
v1.raml (1182, 7): Missing required property content
v1.raml (1187, 9): Unknown node: value
v1.raml (1185, 7): Missing required property content
v1.raml (1190, 9): Unknown node: value
v1.raml (1188, 7): Missing required property content
v1.raml (1196, 7): Unrecognized type 'nil'.
v1.raml (1196, 7): Illegal override of property id inherited from DictionaryItem
v1.raml (1206, 9): Unknown node: value
v1.raml (1204, 7): Missing required property content
v1.raml (1209, 9): Unknown node: value
v1.raml (1207, 7): Missing required property content
v1.raml (1212, 9): Unknown node: value
v1.raml (1210, 7): Missing required property content
v1.raml (1215, 9): Unknown node: value
v1.raml (1213, 7): Missing required property content
v1.raml (1218, 9): Unknown node: value
v1.raml (1216, 7): Missing required property content
v1.raml (1232, 9): Unknown node: value
v1.raml (1230, 7): Missing required property content
v1.raml (1235, 9): Unknown node: value
v1.raml (1233, 7): Missing required property content
v1.raml (1249, 9): Unknown node: value
v1.raml (1247, 7): Missing required property content
v1.raml (1252, 9): Unknown node: value
v1.raml (1250, 7): Missing required property content
v1.raml (1269, 7): Illegal override of property title inherited from DictionaryItem, required property can not be made optional 
v1.raml (1322, 5): Number is expected
v1.raml (1364, 9): Unrecognized type 'datetime'.
v1.raml (1387, 7): Unrecognized type 'nil'.
v1.raml (1387, 7): Illegal override of property id inherited from DictionaryItem
v1.raml (1396, 7): Unrecognized type 'nil'.
v1.raml (1396, 7): Illegal override of property id inherited from DictionaryItem
v1.raml (1410, 9): Unrecognized type 'nil'.
v1.raml (1409, 7): Illegal override of property id inherited from DictionaryItem
v1.raml (1419, 7): Unrecognized type 'datetime'.
v1.raml (1420, 7): Unrecognized type 'datetime'.
v1.raml (1452, 13): Unknown node: value
v1.raml (1452, 13): Missing required property content
v1.raml (1456, 13): Unknown node: value
v1.raml (1456, 13): Missing required property content
v1.raml (1460, 13): Unknown node: value
v1.raml (1460, 13): Missing required property content
v1.raml (1472, 11): Unrecognized type 'nil'.
v1.raml (1482, 11): Unrecognized type 'nil'.
v1.raml (1498, 11): Unrecognized type 'datetime'.
v1.raml (1501, 11): Unrecognized type 'datetime'.
v1.raml (1504, 11): Unrecognized type 'nil'.
v1.raml (1510, 11): Unrecognized type 'nil'.
v1.raml (1600, 9): Unknown node: value
v1.raml (1598, 7): Missing required property content
v1.raml (1603, 9): Unknown node: value
v1.raml (1601, 7): Missing required property content
v1.raml (1606, 9): Unknown node: value
v1.raml (1604, 7): Missing required property content
v1.raml (1609, 9): Unknown node: value
v1.raml (1607, 7): Missing required property content
v1.raml (1618, 9): Unknown node: value
v1.raml (1616, 7): Missing required property content
v1.raml (1629, 9): Unrecognized type 'nil'.
v1.raml (1672, 9): Unrecognized type 'nil'.
v1.raml (1674, 9): Unrecognized type 'nil'.
v1.raml (1676, 9): Unrecognized type 'nil'.
v1.raml (1678, 9): Unrecognized type 'nil'.
v1.raml (1680, 9): Unrecognized type 'nil'.
v1.raml (1688, 9): Unrecognized type 'nil'.
v1.raml (1690, 9): Unrecognized type 'nil'.
v1.raml (1731, 9): Unrecognized type 'datetime'.
v1.raml (1733, 9): Unrecognized type 'datetime'.
v1.raml (1969, 9): Unrecognized type 'nil'.
v1.raml (1970, 5): Required property:subway is missed
v1.raml (1998, 7): Unrecognized type 'datetime'.
v1.raml (2078, 9): Unrecognized type 'datetime'.
v1.raml (2081, 9): Unrecognized type 'datetime'.
v1.raml (2084, 9): Unrecognized type 'nil'.
v1.raml (2163, 9): Unrecognized type 'datetime'.
v1.raml (2166, 9): Unrecognized type 'datetime'.
v1.raml (2253, 13): Unknown node: value
v1.raml (2253, 13): Missing required property content
v1.raml (2265, 9): Unrecognized type 'nil'.
v1.raml (2325, 9): Unrecognized type 'datetime'.
v1.raml (2407, 9): Unrecognized type 'datetime'.
v1.raml (2410, 9): Unrecognized type 'datetime'.
v1.raml (2413, 9): Unrecognized type 'datetime'.
v1.raml (2519, 9): Unrecognized type 'datetime'.
v1.raml (2586, 9): Unrecognized type 'datetime'.
v1.raml (2689, 5): Required property:subway is missed
v1.raml (2758, 9): Unrecognized type 'datetime'.
v1.raml (2796, 13): Unknown node: value
v1.raml (2795, 13): Missing required property content
v1.raml (2798, 13): Unknown node: value
v1.raml (2797, 13): Missing required property content
v1.raml (2800, 13): Unknown node: value
v1.raml (2799, 13): Missing required property content
v1.raml (2802, 13): Unknown node: value
v1.raml (2801, 13): Missing required property content
v1.raml (2896, 13): Unknown node: value
v1.raml (2896, 13): Missing required property content
v1.raml (2901, 13): Unknown node: value
v1.raml (2901, 13): Missing required property content
v1.raml (2911, 13): Unknown node: value
v1.raml (2911, 13): Missing required property content
v1.raml (2917, 13): Unknown node: value
v1.raml (2917, 13): Missing required property content
v1.raml (2923, 13): Unknown node: value
v1.raml (2923, 13): Missing required property content
v1.raml (2925, 9): Unrecognized type 'datetime'.
v1.raml (2929, 9): Unrecognized type 'datetime'.
v1.raml (2933, 9): Unrecognized type 'datetime'.
v1.raml (3007, 9): Unrecognized type 'datetime'.
v1.raml (3054, 9): Unrecognized type 'datetime'.
v1.raml (3057, 9): Unrecognized type 'datetime'.
v1.raml (3060, 9): Unrecognized type 'datetime'.
v1.raml (3090, 13): Unrecognized type 'datetime'.
v1.raml (3277, 9): Unrecognized type 'datetime'.
v1.raml (3365, 9): Unrecognized type 'datetime'.
v1.raml (3480, 9): Unrecognized type 'datetime'.
v1.raml (3483, 9): Unrecognized type 'datetime'.
v1.raml (3486, 9): Unrecognized type 'datetime'.
v1.raml (3489, 9): Unrecognized type 'datetime'.
v1.raml (3492, 9): Unrecognized type 'datetime'.
v1.raml (3495, 9): Unrecognized type 'datetime'.
v1.raml (3553, 7): Unrecognized type 'nil'.
v1.raml (3560, 9): Unrecognized type 'datetime'.
v1.raml (3588, 9): Unrecognized type 'datetime'.
v1.raml (3612, 7): Unrecognized type 'nil'.
v1.raml (3614, 9): Unrecognized type 'datetime'.
v1.raml (3641, 9): Unrecognized type 'datetime'.
v1.raml (3642, 7): Unrecognized type 'nil'.
v1.raml (3680, 9): Unknown node: value
v1.raml (3678, 7): Missing required property content
v1.raml (3683, 9): Unknown node: value
v1.raml (3681, 7): Missing required property content
v1.raml (3705, 9): Unrecognized type 'datetime'.
v1.raml (3748, 9): Unrecognized type 'datetime'.
v1.raml (3788, 7): Unrecognized type 'datetime'.
v1.raml (3870, 9): Unrecognized type 'datetime'.
v1.raml (4408, 7): property body can not have scalar value
v1.raml (4429, 9): property body can not have scalar value
v1.raml (4436, 11): property body can not have scalar value
v1.raml (4446, 9): property body can not have scalar value
v1.raml (4452, 11): property body can not have scalar value
v1.raml (4467, 5): property body can not have scalar value
v1.raml (4526, 13): Unknown node: value
v1.raml (4524, 11): Missing required property content
v1.raml (4529, 13): Unknown node: value
v1.raml (4527, 11): Missing required property content
v1.raml (4532, 13): Unknown node: value
v1.raml (4530, 11): Missing required property content
v1.raml (4535, 13): Unknown node: value
v1.raml (4533, 11): Missing required property content
v1.raml (4598, 9): Unrecognized type 'datetime'.
v1.raml (4601, 9): Unrecognized type 'datetime'.
v1.raml (4648, 7): property body can not have scalar value
v1.raml (4762, 13): Unknown node: value
v1.raml (4760, 11): Missing required property content
v1.raml (4765, 13): Unknown node: value
v1.raml (4763, 11): Missing required property content
v1.raml (4768, 13): Unknown node: value
v1.raml (4766, 11): Missing required property content
v1.raml (4771, 13): Unknown node: value
v1.raml (4769, 11): Missing required property content
v1.raml (4774, 13): Unknown node: value
v1.raml (4772, 11): Missing required property content
v1.raml (4777, 13): Unknown node: value
v1.raml (4775, 11): Missing required property content
v1.raml (4780, 13): Unknown node: value
v1.raml (4778, 11): Missing required property content
v1.raml (4787, 13): Unknown node: value
v1.raml (4785, 11): Missing required property content
v1.raml (4790, 13): Unknown node: value
v1.raml (4788, 11): Missing required property content
v1.raml (4793, 13): Unknown node: value
v1.raml (4791, 11): Missing required property content
v1.raml (4796, 13): Unknown node: value
v1.raml (4794, 11): Missing required property content
v1.raml (4804, 13): Unknown node: value
v1.raml (4802, 11): Missing required property content
v1.raml (4807, 13): Unknown node: value
v1.raml (4805, 11): Missing required property content
v1.raml (4810, 13): Unknown node: value
v1.raml (4808, 11): Missing required property content
v1.raml (4813, 13): Unknown node: value
v1.raml (4811, 11): Missing required property content
v1.raml (4816, 13): Unknown node: value
v1.raml (4814, 11): Missing required property content
v1.raml (4840, 13): Unknown node: value
v1.raml (4838, 11): Missing required property content
v1.raml (4843, 13): Unknown node: value
v1.raml (4841, 11): Missing required property content
v1.raml (4846, 13): Unknown node: value
v1.raml (4844, 11): Missing required property content
v1.raml (4849, 13): Unknown node: value
v1.raml (4847, 11): Missing required property content
v1.raml (4852, 13): Unknown node: value
v1.raml (4850, 11): Missing required property content
v1.raml (4855, 13): Unknown node: value
v1.raml (4853, 11): Missing required property content
v1.raml (4858, 13): Unknown node: value
v1.raml (4856, 11): Missing required property content
v1.raml (4861, 13): Unknown node: value
v1.raml (4859, 11): Missing required property content
v1.raml (4864, 13): Unknown node: value
v1.raml (4862, 11): Missing required property content
v1.raml (4867, 13): Unknown node: value
v1.raml (4865, 11): Missing required property content
v1.raml (4870, 13): Unknown node: value
v1.raml (4868, 11): Missing required property content
v1.raml (4883, 13): Unknown node: value
v1.raml (4881, 11): Missing required property content
v1.raml (4886, 13): Unknown node: value
v1.raml (4884, 11): Missing required property content
v1.raml (4889, 13): Unknown node: value
v1.raml (4887, 11): Missing required property content
v1.raml (4892, 13): Unknown node: value
v1.raml (4890, 11): Missing required property content
v1.raml (4894, 9): Unrecognized type 'datetime'.
v1.raml (4922, 9): property body can not have scalar value
v1.raml (4933, 9): property body can not have scalar value
v1.raml (4954, 5): property body can not have scalar value
v1.raml (4981, 5): property body can not have scalar value
v1.raml (5250, 9): property body can not have scalar value
v1.raml (5365, 13): Unknown node: value
v1.raml (5363, 11): Missing required property content
v1.raml (5368, 13): Unknown node: value
v1.raml (5366, 11): Missing required property content
v1.raml (5371, 13): Unknown node: value
v1.raml (5369, 11): Missing required property content
v1.raml (5374, 13): Unknown node: value
v1.raml (5372, 11): Missing required property content
v1.raml (5376, 9): Unrecognized type 'datetime'.
v1.raml (5466, 13): Unrecognized type 'datetime'.
v1.raml (5521, 5): property body can not have scalar value
v1.raml (5556, 5): property body can not have scalar value
v1.raml (5596, 5): property body can not have scalar value
```

Error stack trace:
```
Error: Api contains errors.
    at toError (/usr/lib/node_modules/raml-php-generator/node_modules/raml-generator/node_modules/raml-1-parser/src/raml1Parser.js:45954:18)
    at /usr/lib/node_modules/raml-php-generator/node_modules/raml-generator/node_modules/raml-1-parser/src/raml1Parser.js:45872:40
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by jenschude** [comment]
This is a error coming from the RAML js parser. So you would have to fix your raml file.

Besides that I'm not actively developing this application anymore. So I would suggest you to fork this project if you want to change the templates or need more functionality.
